language: python

python:
  - "3.6"

env:
  matrix:
    - DJANGO="Django>=1.11,<1.12" # 1.11
    - DJANGO="Django>=2.0,<2.1" # 2.0
    - DJANGO="Django>=2.1,<2.2" # 2.1

cache: pip

install:
  - pip install "$DJANGO" pipenv
  - pipenv lock -r > requirements.txt
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - coverage run --source=easy manage.py test

after_success:
  coveralls
